[package]
name = "bp7"
version = "0.3.4"
authors = ["Lars Baumgaertner <baumgaertner@cs.tu-darmstadt.de>"]
edition = "2018"
description = "Rust implementation of dtn bundle protocol 7 draft https://tools.ietf.org/html/draft-ietf-dtn-bpbis-13"
license = "MIT OR Apache-2.0"
repository    = "https://github.com/gh0st42/bp7-rs"
categories    = ["encoding"]
readme = "README.md"


#[profile.release]
#debug = true

[dev-dependencies]
#criterion = "0.2"

[[bench]]
name = "benchmark"
harness = false

[dependencies]
humantime = "1.2.0"
serde = { version = "1.0", features = ["derive"] }
serde_derive = "1.0.85"
serde_cbor = "0.10"
serde_json = "1.0"
serde_bytes = "0.11"
url = "1.7"
crc = "^1.0.0"
byteorder = "1"
derive_builder = "0.7.1"
rand = "0.7"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
instant = {version = "0.1", features = [ "now" ]}

[target.'cfg(target_arch = "wasm32")'.dependencies]
stdweb = "0.4"
instant = {version = "0.1", features = [ "stdweb", "now" ]}
