[package]
name = "bp7"
version = "0.8.6"
authors = ["Lars Baumgaertner <baumgaertner@cs.tu-darmstadt.de>"]
edition = "2018"
description = "Rust implementation of dtn bundle protocol 7 draft https://tools.ietf.org/html/draft-ietf-dtn-bpbis-31"
license = "MIT OR Apache-2.0"
repository    = "https://github.com/dtn7/bp7-rs"
categories    = ["encoding"]
readme = "README.md"

[profile.release]
#debug = true
lto = true

[lib]
name = "bp7"
crate-type = ["staticlib", "cdylib", "rlib"]

[dev-dependencies]
criterion = "0.3.4"
test-case = "1.1.0"

[build-dependencies]
cbindgen = "0.19.0"

[[bench]]
name = "benchmark"
harness = false

[dependencies]
humantime = "2.1.0"
serde = { version = "1.0.123", features = ["derive"] }
serde_cbor = "0.11.1"
serde_json = "1.0.61"
serde_bytes = "0.11.5"
crc = "2.0.0"
derive_builder = "0.10.2"
thiserror = "1.0.23"
libc = "0.2.98"

# non wasm config

[target.'cfg(not(target_arch = "wasm32"))'.dev-dependencies]
instant = { version = "0.1.9", features = [ "now" ] }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
nanorand = { version = "0.6.0", default-features = true }

# wasm specific

[target.'cfg(target_arch = "wasm32")'.dependencies]
stdweb = "0.4.20"
nanorand = { version = "0.6.0", features = ["getrandom"] }

[target.'cfg(target_arch = "wasm32")'.dev-dependencies]
instant = { version = "0.1.9", features = [ "stdweb", "now" ] }
